---
# data:
qa_data: data/Train_qa_ans.json # data/SampleData_QA.json
risk_data: data/Train_risk_classification_ans.csv # data/SampleData_RiskClassification.csv
dev_qa_data: data/Develop_QA.json
dev_risk_data: data/Develop_risk_classification.csv

# device
device_id: 2 # cpu: -1, gpu: >= 0

# train
seed: 1126
epochs: 10
batch_size: 8
learning_rate: 0.0001
warmup_steps: 20
val_size: 0.2

log_step: 1

# model
model: Roberta
hidden_dim: 256
dropout: 0.2
warmup_epoch: 1
latent_mode: cls
activation: GELU
  
# data processing
max_document_len: 430
max_question_len: 50
spkr: ['民眾', '個管師', '醫師', '護理師', '家屬', '藥師']
use_spkr_token: false