---
# data:
qa_data: data/Train_qa_ans.json # data/SampleData_QA.json
risk_data: data/Train_risk_classification_ans.csv # data/SampleData_RiskClassification.csv
dev_qa_data: data/Develop_QA.json
dev_risk_data: data/Develop_risk_classification.csv
model_path: saved_model/_qa

# train
seed: 1009
epochs: 50
batch_size: 16
learning_rate: 0.0005
warmup_steps: 20
val_size: 0.1

log_step: 1

# model
hidden_dim: 300
n_cls_layers: 3
dropout: 0.25
freeze_bert: true

# data processing
max_document_len: 430
max_question_len: 50
max_choice_len: 32
